FROM openjdk:16-slim
MAINTAINER stupidzhang
ARG JAR_FILE=/target/*.jar
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY ${JAR_FILE} /app.jar
ENV TZ=Asia/Shanghai
EXPOSE 8882
ENTRYPOINT ["sh","-c","java $DEBUG_ARGS $JAVA_OPTS -jar /app.jar"]